<?php

namespace FitcheckerBundle\Repository;

/**
 * ExerciceSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciceSetRepository extends \Doctrine\ORM\EntityRepository
{
}
