<?php

namespace FitcheckerBundle\Repository;

/**
 * SleepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SleepRepository extends \Doctrine\ORM\EntityRepository
{
}
