fitchecker_homepage:
    path:     /
    defaults: { _controller: FitcheckerBundle:Default:index }

fitchecker_user_signup:
    path:     /signup
    defaults: {_controller: FitcheckerBundle:User:signup}

fitchecker_user_login:
    path:     /login
    defaults: { _controller: FitcheckerBundle:User:login}

fitchecker_user_logout:
    path: /logout

fitchecker_user_change_password:
    path:     /profile/changepassword
    defaults: { _controller: FitcheckerBundle:User:changepassword}

fitchecker_user_dashboard:
    path:     /dashboard
    defaults: { _controller: FitcheckerBundle:User:dashboard}

fitchecker_user_show:
    path:     /user/show/{user_id}
    defaults: { _controller: FitcheckerBundle:User:show}
    requirements:
            user_id: '\d+'

fitchecker_user_addExercise:
    path:     /user/{user_id}/addExercise
    defaults: { _controller: FitcheckerBundle:User:addExercise}
    requirements:
            user_id: '\d+'

fitchecker_user_addExerciseSet:
    path:     /user/{user_id}/addSet
    defaults: { _controller: FitcheckerBundle:User:addExerciseSet}
    requirements:
            user_id: '\d+'

fitchecker_user_addConsumption:
    path:     /user/{user_id}/addConsumption
    defaults: { _controller: FitcheckerBundle:User:addConsumption}
    requirements:
            user_id: '\d+'

fitchecker_user_addSleep:
    path:     /user/{user_id}/addSleep
    defaults: { _controller: FitcheckerBundle:User:addSleep}
    requirements:
            user_id: '\d+'

fitchecker_user_getjson:
    path:     /user/{user_id}/getjson
    defaults: { _controller: FitcheckerBundle:User:getJson}
    requirements:
            user_id: '\d+'

fitchecker_exercise_index:
    path:     /exercises
    defaults: { _controller: FitcheckerBundle:Exercise:index}

fitchecker_exercise_add:
    path:     /exercise/add
    defaults: { _controller: FitcheckerBundle:Exercise:add}

fitchecker_equipment_index:
    path:     /equipments
    defaults: { _controller: FitcheckerBundle:Equipment:index}

fitchecker_equipment_add:
    path:     /equipment/add
    defaults: { _controller: FitcheckerBundle:Equipment:add}

fitchecker_admin:
    path:     /admin
    defaults: { _controller: FitcheckerBundle:Default:admin}