FitcheckerBundle\Entity\Equipment:
    type: entity
    table: null
    repositoryClass: FitcheckerBundle\Repository\EquipmentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            column: Name
        location:
            type: string
            length: 255
            nullable: true
            column: Location
    lifecycleCallbacks: {  }
