FitcheckerBundle\Entity\Exercise:
    type: entity
    table: null
    repositoryClass: FitcheckerBundle\Repository\ExerciseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            column: Name
    lifecycleCallbacks: {  }
