FitcheckerBundle\Entity\ExerciceSet:
    type: entity
    table: null
    repositoryClass: FitcheckerBundle\Repository\ExerciceSetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reps:
            type: integer
            column: Reps
    lifecycleCallbacks: {  }
