FitcheckerBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: FitcheckerBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            column: Name
        firstname:
            type: string
            length: 255
            column: Firstname
        age:
            type: integer
            nullable: true
            column: Age
        street:
            type: string
            length: 255
            nullable: true
            column: Street
        streetNumber:
            type: string
            length: 255
            nullable: true
            column: StreetNumber
        zipcode:
            type: string
            length: 255
            nullable: true
            column: Zipcode
        city:
            type: string
            length: 255
            nullable: true
            column: City
        password:
            type: string
            length: 255
            column: Password
    lifecycleCallbacks: {  }
